"""empty message

Revision ID: 2b1938416ea4
Revises: 2f373f71e2ab
Create Date: 2018-06-05 18:52:07.573659

"""

# revision identifiers, used by Alembic.
revision = '2b1938416ea4'
down_revision = '2f373f71e2ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
