"""empty message

Revision ID: af2942ff687e
Revises: 2b1938416ea4
Create Date: 2018-06-06 14:55:20.719765

"""

# revision identifiers, used by Alembic.
revision = 'af2942ff687e'
down_revision = '2b1938416ea4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
